# Generated by Django 3.2.12 on 2023-08-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisicas',
            name='cpf_fisica',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fisicas',
            name='estado_civil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fisicas',
            name='registrado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fisicas',
            name='rg_fisica',
            field=models.FloatField(max_length=50),
        ),
    ]
