# Generated by Django 3.2.12 on 2023-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisicas',
            name='valor_imovel',
            field=models.FloatField(verbose_name='Valor do imóvel'),
        ),
    ]
